/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 1be83cba55cc890d7fdcacbc27b443fd)
interface __BaseEnv_CloudflareEnv {
	MEDIA: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	PRODUCT_NAME: "Built By Me EZ";
	PLATFORM_FEE_BPS: "0";
	SITE_URL: string;
	ADMIN_EMAILS: string;
	VAPID_SUBJECT: string;
	VAPID_PUBLIC_KEY: string;
	VAPID_PRIVATE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PRODUCT_NAME" | "PLATFORM_FEE_BPS" | "SITE_URL" | "ADMIN_EMAILS" | "VAPID_SUBJECT" | "VAPID_PUBLIC_KEY" | "VAPID_PRIVATE_KEY">> {}
}
