/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: d9b2d0301c55ca10733b563e55bbab17)
interface __BaseEnv_CloudflareEnv {
	MEDIA: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	SITE_URL: "https://trainer-kit.example.workers.dev";
	PRODUCT_NAME: "Built By Me EZ";
	PLATFORM_FEE_BPS: "0";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "SITE_URL" | "PRODUCT_NAME" | "PLATFORM_FEE_BPS">> {}
}
