// Custom Worker entry: the OpenNext app for HTTP, plus a cron job that auto-syncs
// trainers' connected YouTube/Vimeo channels. See wrangler.jsonc "triggers".
// @ts-expect-error: generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";
import { vapidFromEnv } from "./lib/push/env";
import { runAutoSync } from "./lib/sync/run";

type Env = CloudflareEnv & Record<string, string | undefined>;

export default {
  fetch: handler.fetch,
  async scheduled(_controller: ScheduledController, env: Env, ctx: ExecutionContext) {
    ctx.waitUntil(runAutoSync(env.DB, { youtubeApiKey: env.YOUTUBE_API_KEY, vimeoToken: env.VIMEO_ACCESS_TOKEN }, vapidFromEnv(env)));
  },
} satisfies ExportedHandler<Env>;
